"""Tests for the error-analysis diagnostic script. Not a re-check of the
actual traces (those live in evaluation/results/error_analysis_traces.json,
generated by running the script against the real agent loop) — just that
build_trace shapes a response correctly and the known-failing IDs are
still valid golden question IDs.
"""

import sys
from dataclasses import dataclass
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import evaluation.run_error_analysis as run_error_analysis
from evaluation.run_llm_eval import load_golden_questions
from src.config import DUCKDB_PATH

pytestmark = pytest.mark.skipif(not DUCKDB_PATH.exists(), reason="warehouse not built yet")


def test_known_failing_ids_are_all_valid_golden_question_ids():
    ids = {q["id"] for q in load_golden_questions()}
    assert set(run_error_analysis.KNOWN_FAILING_IDS) <= ids


@dataclass
class FakeResult:
    rows: list


@dataclass
class FakeAttempt:
    sql: str
    result: object
    error: object
    valid: bool
    validation_reason: str


@dataclass
class FakeResponse:
    attempts: list
    final_sql: object
    final_result: object
    succeeded: bool


def test_build_trace_shapes_a_response_with_multiple_attempts():
    q = {"id": "t2_13", "tier": 2, "question": "orders in Germany", "reference_result": [[6029]]}
    response = FakeResponse(
        attempts=[
            FakeAttempt("SELECT 1", None, "binder error", False, "execution failed"),
            FakeAttempt("SELECT 2", FakeResult([(6029,)]), None, True, "Result looks plausible."),
        ],
        final_sql="SELECT 2",
        final_result=FakeResult([(6029,)]),
        succeeded=True,
    )

    trace = run_error_analysis.build_trace(q, response)

    assert trace["question_id"] == "t2_13"
    assert len(trace["attempts"]) == 2
    assert trace["attempts"][0]["error"] == "binder error"
    assert trace["attempts"][1]["result_rows"] == [(6029,)]
    assert trace["final_result_rows"] == [(6029,)]
    assert trace["succeeded_per_validate_result"] is True


def test_build_trace_handles_a_response_with_no_final_result():
    q = {"id": "t2_14", "tier": 2, "question": "revenue last quarter", "reference_result": [[1]]}
    response = FakeResponse(
        attempts=[FakeAttempt("SELECT bad", None, "type error", False, "execution failed")],
        final_sql="SELECT bad",
        final_result=None,
        succeeded=False,
    )

    trace = run_error_analysis.build_trace(q, response)

    assert trace["final_result_rows"] is None
    assert trace["succeeded_per_validate_result"] is False
