"""Tests for the Tier-3 retrieval ablation script. Most of the heavy
machinery (run_combination, summarize, results_match) is imported
directly from evaluation/run_llm_eval.py and already covered by
tests/test_run_llm_eval.py — these tests cover what's specific to the
ablation: scoping to Tier 3 only, and the generated report/outcomes
files. Not a re-check of the actual measured accuracy (that lives in
evaluation/results/ablation_eval.md, generated by running the script
against real models).
"""

import json
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import evaluation.run_ablation as run_ablation
from src.config import DUCKDB_PATH

pytestmark = pytest.mark.skipif(not DUCKDB_PATH.exists(), reason="warehouse not built yet")


def test_load_tier3_questions_returns_ten_tier3_only():
    questions = run_ablation.load_tier3_questions()
    assert len(questions) == 10
    assert all(q["tier"] == 3 for q in questions)


def test_condition_labels_cover_both_prompt_names():
    assert run_ablation.CONDITION_LABELS["baseline"] == "retrieval disabled"
    assert run_ablation.CONDITION_LABELS["schema-grounded"] == "retrieval enabled"


def test_results_file_was_generated_with_expected_sections():
    content = run_ablation.RESULTS_PATH.read_text(encoding="utf-8")
    assert "retrieval disabled" in content
    assert "retrieval enabled" in content
    assert "llama3" in content
    assert "gpt-4o-mini" in content
    assert "Corroboration against Day 11" in content


def test_outcomes_file_has_one_entry_per_question_per_combination():
    outcomes = json.loads(run_ablation.OUTCOMES_PATH.read_text(encoding="utf-8"))
    # 10 Tier-3 questions x 2 models x 2 conditions
    assert len(outcomes) == 40
    assert all("sql" in o and "correct" in o and "model" in o and "condition" in o for o in outcomes)
